name: Release to Maven Central
run-name: Release to Maven Central on ${{ github.ref }}

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: 'ossrh'
          cache: 'maven'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          
      - name: Verify the build configuration
        run: mvn --batch-mode validate -Prelease,release-ossrh
        
      - name: Prepare the release
        run: mvn --batch-mode -Prelease,release-ossrh -Dresume=false release:prepare
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        
      - name: Deploy to Maven Central
        run: mvn --batch-mode -Prelease,release-ossrh release:perform
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          
      - name: Push version to repository
        run: git push --tags origin master
