name: Deploy to Maven Central
run-name: Deploy to Maven Central on ${{ github.ref }}

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MAVEN_CMD: mvn --batch-mode -Prelease,release-ossrh
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure Maven Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: 'ossrh'
          cache: 'maven'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          
      - name: Validate the POM configuration
        run: ${{ env.MAVEN_CMD }} validate
          
      - name: Deploy to Maven Central
        run: ${{ env.MAVEN_CMD }} deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
