name: Release to Maven Central
run-name: Release to Maven Central on ${{ github.ref }}

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      # enable the release and release-ossrh profiles
      MAVEN_CMD: mvn --batch-mode -P release,release-ossrh
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      
      - name: Configure Maven Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: 'ossrh'
          cache: 'maven'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          
      - name: Validate the POM configuration
        run: ${MAVEN_CMD} validate
        
      - name: Prepare the release
        run: ${MAVEN_CMD} -D resume=false release:prepare
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        
      - name: Deploy to Maven Central
        run: ${MAVEN_CMD} release:perform
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          
      - name: Push tag and updated pom files to project
        run: git push --tags origin ${GITHUB_REF}
